import { CONTROLLER_ADDRESS } from '../index'
import ARTH_INCENTIVE_CONTROLLER_ABI from './arthController.json'

const ARTH_INCENTIVE_CONTROLLER = CONTROLLER_ADDRESS

export { ARTH_INCENTIVE_CONTROLLER_ABI, ARTH_INCENTIVE_CONTROLLER }
